---
title: "Final Report"
author: "Youngsoo Baek"
date: "Aug 18th, 2018"
output: pdf_document
---

# What I Did This Summer

I took a straightforward, relatively simple spatiotemporal model that involves a mixed regression model with eigenvectors derived from Moran's $I$ basis expansion and studied its efficacy in real-life data context. Specifically, the expansive QWI economic dataset that was already studied in past literature for a different model was explored and used as primary data to study model performance. Results suggest many avenues of possible improvement to the model and new issues, which will lead to exploration of more dynamic-structured models.

# Poster Materials

* I did an extensive literature review of different parametric spatiotemporal models currently suggested and compared their relative merits and shared perspectives in their approaching high-dimesional model specification.


* I explored the adequacy of the suggested adjacency matrix structure in the existing literature that is integral to model specification in a simulated time series context. 


  - I also suggested a possible heuristic-based modification for accommodating seasonal structure of the data.
  
  
* I tested the model on real-life data, collected by the U.S. Census Bureau, and explored different model specifications to conclude several improvements that need to be made on this modeling approach.

# Unincluded Work Explained

I first analyzed the NOAA Local Climatological Data by subsetting it to specific regions as suggested by Prof. Tupper. As it became clearer what interested me as of the moment in the particular area of research, I decided my understanding of modeling for point-level data, with possibly complex issues with spatial/temporal support involved, was not yet fully grown and shifted onto QWI dataset that was already tried and tested in past literature.

While unincluded in my poster, a major portion of my work went into understanding, and seeking places for improvements in, a new class of multivariate dynamic spatiotemporal model recently suggested. Since this particular class of model takes an inherently different approach to modeling, in that it does not attempt to summarize the information about the marginal distribution in moments, the work ended up being omitted in the poster. 

Since this summer's work made clear certain limiations imposed on employing traditional mixture regression model for very high-dimensional, spatially correlated data, my future work will mainly focus on:

i) Relaxing AR(1) assumption of the spatiotemporal model and extending it to account for longer-lagged dependencies;


ii) Extending the suggested model framework to point-level spatial support and continuous temporal support.

A considerable amount of my research time ended up going into reading past literature. Spatiotemporal modeling is a relatively new subfield of statistics for which there remains a lot to be explored. Different models, as much as they can be classified into certain classes (e.g., "marginal" vs. "dynamic"), tend to tackle the specific issues suggested by the data at hand rather than formulate a flexible general framework. Understanding of this fact was a major take-away of the research that will provide avenues for future work.


Since the codes that I most direly needed (implementing MSTM framework) was not available yet in public, and since the eigenvector filtering model included in the poster also did not have available codes in R, much coding time has been spent on "reinventing the wheel" and reimplementing these models through R. Packages like `ngspatial` by J. Hughes were immensely helpful in the process, and I "tweaked" some of the methods in the package that were not explicitly provided on the interface. I am currently in the process of completing the codes that can reproduce the MSTM modeling results in the existing literature.

# Results of Journal Hunt

A brief list of some of the journals that I find appropriate for publishing my current and future work in this topic.

i) _Spatial Statistics._ This journal, featured on Elsevier platform, partly supports open access materials and is a major platform for publishing forefront work on spatial / spatiotemporal statistics. The journal introduction says that it "favours manuscripts that present theory generated by new applications, or in which new theory is applied to an important practical case." It also says that a "purely theoretical study will only rarely be accepted," while "case studies without methodological development are not acceptable for publication" also. I believe this hits the perfect balance point between theory and application, something my future work (especially my senior thesis topic as of now) will definitely address. The editors board also include several authors (i.e., C. Wikle, D. Griffith) with whose work's direction I have come to have great familiarity.

ii) _Journal of Multivariate Analysis._ This journal, featured on Elsevier platofrm, actively supports open access articles; any article that is older than 48 months is included in the open access archive. The availability of an open access archive will be practically useful in publication aspect, as I can easily tailor certain extensions made to my methodological work. Furthermore, since the dynamic modeling framework I am mainly interested in is multivariate in nature, it is natural to consider publication in this journal which "welcomes contributions to all aspects of multivariate data analysis and modeling" and "substantial contributions to regression or time series analysis for multidimensional response variables."

iii) _Stat._ This journal, while most likely lacking in its "impact factors" compared to the former two journals, is probably a practically appealing avenue for publication. The journal introduction pages makes it clear that the motto behind its publication is rapid dissemination of any academic contributions to statistics that are on the forefront, topical issues. It has "a single pass, high quality review process that aims to publish within 30 days of submission" and features "a maximum article length of 10 pages of text." While it is welcome to any article related to statistics or interdisciplinary studies involving statistics, a major factor of consideration here is that two of the papers published by Bradley, Wikle, and Holan that deal with minor extensions to their MSTM framework were published here in the last 3 years.


# Two or Three Things I Learned This Summer

* __How to do literature review.__ Since I did not have a clearly formulated understanding of which avenue I wanted to pursue this summer, and since reading papers related to modeling and methodology required considerable background knowledge and mathematical maturity, literature review tended to always consume much more time than I expected. Often I found myself becoming short-sighted, putting much efforts into understanding technical difficulties and ending up being stranded onto papers that are not necessarily helpful to my overall understanding of what I wanted to do. The experience was that of trial-and-error, however; I believe I am now much more equipped for a systematic literature review process, and thus a better method of learning technical results I need to know before getting onto actual work. _To be systematic and strategic about hunting literature in a field that I am newly coming into is probably the prime advice I want to give to my past self at this point,_ since it will just facilitate finding out what I actually want to do very early on.


* __Efficient use and allocation of research work hours.__ A day in the research routine certainly flows very differently from a day in the semester where I take four classes, a seemingly obvious fact that took me quite a long time to realize. While I initially set up a plan to keep a regular nine-to-five routine schedule for research work, so that the work will not intervene with my free hours, overall this plan did not work so well mainly because of certain personal, stressful issues and because I was not used to this strict division between work and free hours. While the divide probably does not have to be too strict, I also learned that tackling my research work like writing a paper for a class or solving a problem set was in general a very unwise and unhealthy choice of action that more hurts than reinforces my productivity. Next research experience, I will be more prepared in an efficient and sound allocation of time for research work.

# Acknowledgements

I hereby want to thank you, Professor Tupper, for being such a helpful and encouraging advisor for my summer research (and the very first academically serious one involved in statistics). While there were many stressful factors that hindered my focusing on work that I did not confide in you, you were always very encouraging even about the most minor progress I have made and provided a very practical, helpful perspective in approaching academic research. In particular, your advice on tackling a daunting task of reading publications and a rundown on the insights behind mixed regression model were immensely helpful. I believe this summer work motivated me to further explore the issues that arise in modeling spatiotemporal data (or, more in general, very high-dimensional data with correlation structures) and apply new methodologies to very intriguing real-life datasets. 

Since it probably needs more time to organize at this point (given the immediacy of my graduate school applications), I will prepare a separate write-up or an e-mail for which I will list useful information for you writing a recommendation letter for me in the near future.
